/**
 * Hulmane-The-Saga — Kannada Language Strings (ಕನ್ನಡ)
 */
(function () {
  'use strict';

  window.MH_LANG.register('kn', 'ಕನ್ನಡ', {
    // Navigation
    'nav.home': 'ಮುಖಪುಟ',
    'nav.characters': 'ವೀರರು',
    'nav.regions': 'ಪ್ರದೇಶಗಳು',
    'nav.council': 'ಮಹಾಸಭೆ',
    'nav.story': 'ಕಥೆ',
    'nav.tattoo': 'ಹಚ್ಚೆ ವ್ಯವಸ್ಥೆ',
    'nav.family_tree': 'ವಂಶವೃಕ್ಷ',

    // Index page
    'index.title': 'ಮಹಾಹುಲ್ಮನೆ',
    'index.subtitle': 'ಮಹಾ ಸಾಮ್ರಾಜ್ಯ',
    'index.tagline': 'ನಾಡಿನ ಪ್ರತಿಯೊಂದು ಮೂಲೆಯಿಂದ ವೀರರು ಉದಯಿಸುವ ಸ್ಥಳ',
    'index.enter': 'ಸಾಮ್ರಾಜ್ಯವನ್ನು ಪ್ರವೇಶಿಸಿ',
    'index.skip': 'ಪರಿಚಯ ಬಿಟ್ಟುಬಿಡಿ',
    'index.overview': 'ಜಗತ್ತಿನ ಅವಲೋಕನ',
    'index.tattoo_teaser': 'ಪವಿತ್ರ ಹಚ್ಚೆ',
    'index.tattoo_desc': 'ಈ ನಾಡಿನಲ್ಲಿ ಹುಟ್ಟಿದ ಪ್ರತಿ ಮಗುವಿಗೆ ಒಂದು ಗುರುತು ಇರುತ್ತದೆ — ಅವರ ಕುಲ ಪ್ರಾಣಿಯ ಹೆಜ್ಜೆ ಗುರುತು. ಅವರು ತಮ್ಮ ಯೋಗ್ಯತೆಯನ್ನು ಸಾಬೀತುಪಡಿಸಿದಂತೆ, ಹಚ್ಚೆ ಬೆಳೆಯುತ್ತದೆ.',
    'index.hierarchy_title': 'ಶ್ರೇಣಿ ವ್ಯವಸ್ಥೆ',
    'index.hierarchy_desc': 'ರಾಜ್ಯ ಚಾಂಪಿಯನ್‌ಗಳು ಪ್ರಾದೇಶಿಕ ನಾಯಕರಾಗಿ ಏರಿಕೆಯಾಗುತ್ತಾರೆ, ನಂತರ ಮಹಾಸಭೆಗೆ — ಜಗತ್ತಿನ ಅತ್ಯಂತ ಶಕ್ತಿಶಾಲಿ ಯೋಧರು.',
    'index.threat_title': 'ಬರುತ್ತಿರುವ ಬಿರುಗಾಳಿ',
    'index.threat_desc': 'ಶೂನ್ಯ ಬಾಯಿ ಹತ್ತಿರ ಬರುತ್ತಿದೆ — ಲೋಕಗಳನ್ನು ನುಂಗುವ ಪುರಾತನ ಬ್ರಹ್ಮಾಂಡ ಶಕ್ತಿ. ಒಗ್ಗಟ್ಟಾಗಿ ಮಾತ್ರ ರಾಜ್ಯಗಳು ಬದುಕಬಹುದು.',
    'index.explore_map': 'ನಕ್ಷೆಯನ್ನು ಅನ್ವೇಷಿಸಿ',
    'index.featured': 'ಪ್ರಮುಖ ವೀರರು',

    // Characters page
    'chars.title': 'ಸಾಮ್ರಾಜ್ಯದ ವೀರರು',
    'chars.subtitle': '೨೮ ಚಾಂಪಿಯನ್‌ಗಳು — ಪ್ರತಿ ರಾಜ್ಯದಿಂದ ಒಬ್ಬರು',
    'chars.filter_region': 'ಪ್ರದೇಶದ ಪ್ರಕಾರ ಶೋಧಿಸಿ',
    'chars.filter_gender': 'ಲಿಂಗದ ಪ್ರಕಾರ ಶೋಧಿಸಿ',
    'chars.all': 'ಎಲ್ಲಾ',
    'chars.male': 'ಪುರುಷ',
    'chars.female': 'ಮಹಿಳೆ',

    // Regions
    'region.south': 'ದಕ್ಷಿಣ ಭಾರತ',
    'region.west': 'ಪಶ್ಚಿಮ ಭಾರತ',
    'region.east': 'ಪೂರ್ವ ಭಾರತ',
    'region.north': 'ಉತ್ತರ ಭಾರತ',
    'region.northeast': 'ಈಶಾನ್ಯ ಭಾರತ',
    'region.central': 'ಮಧ್ಯ ಭಾರತ',

    // Hero detail
    'hero.overview': 'ಅವಲೋಕನ',
    'hero.backstory': 'ಹಿನ್ನೆಲೆ ಕಥೆ',
    'hero.tattoo_progress': 'ಹಚ್ಚೆ ಪ್ರಗತಿ',
    'hero.appearance': 'ರೂಪ',
    'hero.personality': 'ವ್ಯಕ್ತಿತ್ವ',
    'hero.fighting_style': 'ಹೋರಾಟ ಶೈಲಿ',
    'hero.weapon': 'ಆಯುಧ',
    'hero.origin': 'ಮೂಲ',
    'hero.summary': 'ಸಾರಾಂಶ',
    'hero.family_drama': 'ಕುಟುಂಬ ನಾಟಕ',

    // Tattoo system
    'tattoo.title': 'ಪವಿತ್ರ ಹಚ್ಚೆ ವ್ಯವಸ್ಥೆ',
    'tattoo.subtitle': 'ಶಕ್ತಿಯ ಗುರುತು',
    'tattoo.stage1': 'ಹೆಜ್ಜೆ ಗುರುತು',
    'tattoo.stage1_desc': 'ಕುಲದಲ್ಲಿ ಹುಟ್ಟಿದ — ಜನ್ಮತಃ ಸ್ವಯಂಚಾಲಿತ',
    'tattoo.stage2': 'ಕಾಲುಗಳು',
    'tattoo.stage2_desc': 'ಮೊದಲ ಪರೀಕ್ಷೆ ಉತ್ತೀರ್ಣ — ಸಮುದಾಯ ಮನ್ನಣೆ',
    'tattoo.stage3': 'ಅರ್ಧ ದೇಹ',
    'tattoo.stage3_desc': 'ಪ್ರಾದೇಶಿಕ ಚಾಂಪಿಯನ್ — ಸಾಬೀತಾದ ಯೋಧ',
    'tattoo.stage4': 'ಪೂರ್ಣ ರೂಪ',
    'tattoo.stage4_desc': 'ಸಮುದಾಯ ನಾಯಕ — ರಾಜ್ಯ ವೀರ',
    'tattoo.combination': 'ಸಂಯೋಜನೆ ಹಚ್ಚೆಗಳು',
    'tattoo.combination_desc': 'ಪ್ರಾದೇಶಿಕ ನಾಯಕರು ವಿಲೀನ ಹಚ್ಚೆಗಳನ್ನು ಹೊಂದಿರುತ್ತಾರೆ — ತಮ್ಮ ಪ್ರದೇಶದ ಪ್ರತಿ ರಾಜ್ಯ ಪ್ರಾಣಿಯ ಲಕ್ಷಣಗಳು',
    'tattoo.demo': 'ಸಂವಾದಾತ್ಮಕ ಪ್ರದರ್ಶನ',
    'tattoo.select_animal': 'ಪ್ರಾಣಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'tattoo.lore': 'ಐತಿಹ್ಯ ಮತ್ತು ನಿಯಮಗಳು',
    'tattoo.gallery': 'ಪ್ರಾಣಿ ಗ್ಯಾಲರಿ',

    // Regions page
    'regions.title': 'ಸಾಮ್ರಾಜ್ಯದ ಪ್ರದೇಶಗಳು',
    'regions.subtitle': 'ಆರು ಪ್ರದೇಶಗಳು — ಆರು ನಾಯಕರು',
    'regions.hierarchy': 'ಶ್ರೇಣಿ ವ್ಯವಸ್ಥೆ',
    'regions.tier_state': 'ರಾಜ್ಯ ವೀರರು',
    'regions.tier_regional': 'ಪ್ರಾದೇಶಿಕ ನಾಯಕರು',
    'regions.tier_council': 'ಮಹಾಸಭೆ',
    'regions.tier_kingdom': 'ಮಹಾಹುಲ್ಮನೆ ಸಾಮ್ರಾಜ್ಯ',
    'regions.comparison': 'ಪ್ರದೇಶ ಹೋಲಿಕೆ',

    // Council page
    'council.title': 'ಮಹಾಸಭೆ',
    'council.subtitle': 'ತಿಳಿದ ಜಗತ್ತಿನ ಆಡಳಿತಗಾರರು',
    'council.india': 'ಭಾರತ',
    'council.world': 'ವಿಶ್ವ',
    'council.space': 'ಬಾಹ್ಯಾಕಾಶ',
    'council.hybrid': 'ಸಂಕರ',
    'council.threat': 'ಶೂನ್ಯ ಬಾಯಿ',
    'council.threat_desc': 'ಬ್ರಹ್ಮಾಂಡ ಶಕ್ತಿ ನಕ್ಷತ್ರಪುಂಜದ ಆಚೆಯಿಂದ ಹತ್ತಿರ ಬರುತ್ತಿದೆ. ಒಗ್ಗಟ್ಟಾದ ಸಭೆ ಮಾತ್ರ ಈ ಬೆದರಿಕೆಯನ್ನು ಎದುರಿಸಬಹುದು.',

    // Story page
    'story.title': 'ಮಹಾಕಾವ್ಯ',
    'story.subtitle': 'ಪುರಾತನ ಕಾಲದಿಂದ ಅಂತಿಮ ಯುದ್ಧದವರೆಗೆ',
    'story.timeline': 'ಕಾಲರೇಖೆ',
    'story.chapters': 'ಅಧ್ಯಾಯಗಳು',
    'story.deep_dives': 'ಆಳವಾದ ಕಥೆಗಳು',

    // Common
    'common.close': 'ಮುಚ್ಚಿ',
    'common.read_more': 'ಮತ್ತಷ್ಟು ಓದಿ',
    'common.back': 'ಹಿಂದೆ',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'common.language': 'ಭಾಷೆ',

    // Hero names in Kannada
    'hero.name.andhra-pradesh': 'ಕೃಷ್ಣವೇಣಿ',
    'hero.name.telangana': 'ಚಿತ್ತರಂಗ',
    'hero.name.karnataka': 'ತುಂಗಭದ್ರಾ',
    'hero.name.kerala': 'ಪರಶುರಾಮ',
    'hero.name.tamil-nadu': 'ಕುರಿಂಜಿಸೆಲ್ವಿ',
    'hero.name.gujarat': 'ಸಿಂಹವಿಕ್ರಮ',
    'hero.name.maharashtra': 'ಶಿವಗತಿ',
    'hero.name.rajasthan': 'ಮೃಗತೃಷ್ಣಾ',
    'hero.name.goa': 'ಸಾಗರದೇವ',
    'hero.name.west-bengal': 'ಸುಂದರವಾಣಿ',
    'hero.name.odisha': 'ಜಗನ್ನಾಥಿ',
    'hero.name.bihar': 'ವಜ್ರಮುಖ',
    'hero.name.jharkhand': 'ವನಜಾರ',
    'hero.name.uttar-pradesh': 'ಗಂಗಾಪುತ್ರ',
    'hero.name.madhya-pradesh': 'ದ್ವಾದಶಶೃಂಗ',
    'hero.name.punjab': 'ಪಂಚನದ',
    'hero.name.haryana': 'ಕುರುಕ್ಷೇತ್ರಾ',
    'hero.name.himachal-pradesh': 'ಹಿಮವತಿ',
    'hero.name.uttarakhand': 'ಕಸ್ತೂರಿಕಾ',
    'hero.name.assam': 'ಕಮಲವರ್ಣ',
    'hero.name.arunachal-pradesh': 'ಉದಯಗಿರಿ',
    'hero.name.nagaland': 'ಜುಲೆವೀರಾ',
    'hero.name.meghalaya': 'ಮೇಘನಾದಿ',
    'hero.name.manipur': 'ಮೊಯ್ರಾಂಗ್ಥೆಮ್',
    'hero.name.mizoram': 'ತ್ಲಾಂಗ್ವಾಲ',
    'hero.name.tripura': 'ತ್ರಿಪುರಾರಿ',
    'hero.name.sikkim': 'ಕಾಂಚನಜಂಘ',
    'hero.name.chhattisgarh': 'ದಂಡಕಾರ್ಣಿ',

    // Hero titles in Kannada
    'hero.title.andhra-pradesh': 'ನದಿಯ ಮಗಳು',
    'hero.title.telangana': 'ಚುಕ್ಕೆಗಳ ಕತ್ತಿ',
    'hero.title.karnataka': 'ಗುಪ್ತ ದೇವಾಲಯದ ರಕ್ಷಕಿ',
    'hero.title.kerala': 'ಕೊಡಲಿ ಯೋಧ ಪುನರ್ಜನ್ಮ',
    'hero.title.tamil-nadu': 'ಕುರಿಂಜಿ ಹೂವಿನ ಮಗಳು',
    'hero.title.gujarat': 'ಸಿಂಹದ ಶೌರ್ಯ',
    'hero.title.maharashtra': 'ಶಿವನ ಕೃಪೆ',
    'hero.title.rajasthan': 'ಮರುಭೂಮಿಯ ಮರೀಚಿಕೆ',
    'hero.title.goa': 'ಸಾಗರದ ಒಡೆಯ',
    'hero.title.west-bengal': 'ಸುಂದರಬನದ ಧ್ವನಿ',
    'hero.title.odisha': 'ಜಗತ್ತಿನ ಒಡತಿ',
    'hero.title.bihar': 'ವಜ್ರಮುಖ',
    'hero.title.jharkhand': 'ಕಾಡಿನ ಅಲೆಮಾರಿ',
    'hero.title.uttar-pradesh': 'ಗಂಗೆಯ ಮಗ',
    'hero.title.madhya-pradesh': 'ಹನ್ನೆರಡು ಕೊಂಬಿನವ',
    'hero.title.punjab': 'ಐದು ನದಿಗಳ ಯೋಧ',
    'hero.title.haryana': 'ಪವಿತ್ರ ಕ್ಷೇತ್ರದ ಮಗಳು',
    'hero.title.himachal-pradesh': 'ಹಿಮದ ಮಗಳು',
    'hero.title.uttarakhand': 'ಕಸ್ತೂರಿ ಧಾರಿಣಿ',
    'hero.title.assam': 'ಕಮಲ ವರ್ಣದವಳು',
    'hero.title.arunachal-pradesh': 'ಸೂರ್ಯೋದಯದ ಬೆಟ್ಟ',
    'hero.title.nagaland': 'ಜುಕೋ ಕಣಿವೆಯ ಆತ್ಮ',
    'hero.title.meghalaya': 'ಮೋಡ-ಗುಡುಗು',
    'hero.title.manipur': 'ತೇಲುವ ಹುಲ್ಲುಗಾವಲಿನ ರಕ್ಷಕ',
    'hero.title.mizoram': 'ಬೆಟ್ಟದ ಕಾವಲುಗಾರ',
    'hero.title.tripura': 'ಮೂರು ನಗರಗಳ ವಿಜೇತ',
    'hero.title.sikkim': 'ಹಿಮದ ಐದು ನಿಧಿಗಳು',
    'hero.title.chhattisgarh': 'ದಂಡಕ ವನದವಳು',

    // State names in Kannada
    'state.andhra-pradesh': 'ಆಂಧ್ರ ಪ್ರದೇಶ',
    'state.telangana': 'ತೆಲಂಗಾಣ',
    'state.karnataka': 'ಕರ್ನಾಟಕ',
    'state.kerala': 'ಕೇರಳ',
    'state.tamil-nadu': 'ತಮಿಳುನಾಡು',
    'state.gujarat': 'ಗುಜರಾತ್',
    'state.maharashtra': 'ಮಹಾರಾಷ್ಟ್ರ',
    'state.rajasthan': 'ರಾಜಸ್ಥಾನ',
    'state.goa': 'ಗೋವಾ',
    'state.west-bengal': 'ಪಶ್ಚಿಮ ಬಂಗಾಳ',
    'state.odisha': 'ಒಡಿಶಾ',
    'state.bihar': 'ಬಿಹಾರ',
    'state.jharkhand': 'ಜಾರ್ಖಂಡ್',
    'state.uttar-pradesh': 'ಉತ್ತರ ಪ್ರದೇಶ',
    'state.madhya-pradesh': 'ಮಧ್ಯ ಪ್ರದೇಶ',
    'state.punjab': 'ಪಂಜಾಬ್',
    'state.haryana': 'ಹರಿಯಾಣ',
    'state.himachal-pradesh': 'ಹಿಮಾಚಲ ಪ್ರದೇಶ',
    'state.uttarakhand': 'ಉತ್ತರಾಖಂಡ',
    'state.assam': 'ಅಸ್ಸಾಂ',
    'state.arunachal-pradesh': 'ಅರುಣಾಚಲ ಪ್ರದೇಶ',
    'state.nagaland': 'ನಾಗಾಲ್ಯಾಂಡ್',
    'state.meghalaya': 'ಮೇಘಾಲಯ',
    'state.manipur': 'ಮಣಿಪುರ',
    'state.mizoram': 'ಮಿಜೋರಾಂ',
    'state.tripura': 'ತ್ರಿಪುರ',
    'state.sikkim': 'ಸಿಕ್ಕಿಂ',
    'state.chhattisgarh': 'ಛತ್ತೀಸ್‌ಗಢ'
  });
})();
